server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/microservice_db
    driverClassName: com.mysql.cj.jdbc.Driver
    username: root
    password: Akhil@1998
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true